import type {NextPage} from 'next'
import Head from 'next/head'
import {PageLayout} from "../../components/layout/PageLayout/PageLayout";

const Catalog: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Catalog</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <PageLayout>
                <h1>Catalog</h1>
            </PageLayout>
        </div>
    )
}

export default Catalog;
