import type {NextPage} from 'next'
import Head from 'next/head'

const Catalog: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Catalog</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <h1>Catalog</h1>
        </div>
    )
}

export default Catalog;
