import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { CatalogPage } from '../../components/pages/CatalogPage/CatalogPage';
import { RootState } from '../../store/store';
import { WithRedux } from '../../components/redux/WithRedux';

const Catalog: NextPage<{ serverSideRootState: RootState }> = ({ serverSideRootState }) => {
	return (
		<WithRedux preloadedState={serverSideRootState}>
			<div>
				<Head>
					<title>Catalog</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<CatalogPage serverSideRootState={serverSideRootState} />
			</div>
		</WithRedux>
	);
};

export const getServerSideProps = async () => {
	// TODO - здесь должен быть запрос по query-параметрам на бек чтобы дать инициализированное состояние для стора (catalogState)
	return {
		props: {
			serverSideRootState: {
				catalogState: {
					currentPage: 1,
					pageSize: 10,
					products: [],
					filters: {
						price: null,
						sort: null,
						companyProducers: null
					}
				}
			}
		}
	};
};

export default Catalog;
