import type {NextPage} from 'next'
import Head from 'next/head'
import {PageLayout} from "../components/layout/PageLayout/PageLayout";
import {MainPage} from "../components/pages/MainPage/MainPage";
import React from "react";
import {WithRedux} from "../components/redux/WithRedux";
import {EAsync} from "../enum/EAsync";

interface MainProps {
    preloadedState: any;
}

const Main: NextPage<MainProps> = ({preloadedState}) => {
    return (
        <WithRedux preloadedState={preloadedState}>
            <div>
                <Head>
                    <title>Главная</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <PageLayout>
                    <MainPage/>
                </PageLayout>
            </div>
        </WithRedux>
    )
}

export const getStaticProps = () => {
    return {
        props: {
            preloadedState: {
                mainPageState: {
                    mainScreenSmartphones: [], loadingState: EAsync.ERROR
                }
            }
        }
    }
}

export default Main;
