import type {NextPage} from 'next'
import Head from 'next/head'
import {PageLayout} from "components/layout/PageLayout/PageLayout";
import {MainPage} from "components/pages/MainPage/MainPage";
import React from "react";
import {WithRedux} from "components/redux/WithRedux";
import {EAsync} from "enum/EAsync";
import {smartphonesForMainScreen} from "database/temp";
import {RootState} from "store/store";

const Main: NextPage<{ serverSideRootState: RootState }> = ({serverSideRootState}) => {
    return (
        <WithRedux preloadedState={serverSideRootState}>
            <div>
                <Head>
                    <title>Главная</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <PageLayout>
                    <MainPage serverSideRootState={serverSideRootState}/>
                </PageLayout>
            </div>
        </WithRedux>
    )
}

export const getStaticProps = async () => {
    return {
        props: {
            serverSideRootState: {
                mainPageState: {
                    mainScreen: {
                        mainScreenSmartphones: smartphonesForMainScreen,
                        loadingState: EAsync.SUCCESS,
                        activeSmartphoneIndex: 0,
                    }
                }
            }
        }
    }
}

export default Main;
